baseline: B1
seed: 42
num_classes: 8

experiment:
  name: "Baseline_B1"
  description: "Single-frame ResNet50 baseline for volleyball group activity recognition"
  version: 1

data:
  annot_file: data_set/annot_all.pkl
  videos_dir: data_set
  splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    val: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

labels:
  class_names: 
    - r_set
    - r_spike
    - r-pass
    - r_winpoint
    - l_winpoint
    - l-pass
    - l-spike
    - l_set

training:
  epochs: 40
  batch_size: 32
  lr: 0.0001
  optimizer: AdamW
  weight_decay: 0.0001
  num_workers: 4
  mixup: False
  scheduler: "ReduceLROnPlateau"


output:
  base_dir: outputs/B1
  checkpoints_dir: outputs/B1/checkpoints
  results_dir: outputs/B1/results
  mlruns_dir: outputs/B1/mlruns
