baseline: B3
seed: 42
num_classes: 9

experiment:
  name: "Baseline_B3"
  description: "ResNet50 baseline for single-frame person action recognition with player crops"
  version: 1


data:
  annot_file: data_set/annot_all.pkl
  videos_dir: data_set
  splits:
    train: [7, 10]
    val: [10]
    test: [7]

labels:
  class_names:
    - waiting
    - setting
    - digging
    - falling
    - spiking
    - blocking
    - jumping
    - moving
    - standing

training:
  epochs: 7
  batch_size: 3
  lr: 0.0001
  optimizer: AdamW
  weight_decay: 0.0001
  num_workers: 4
  mixup: False
  scheduler: "StepLR"
  

output:
  base_dir: outputs/B3
  checkpoints_dir: outputs/B3/checkpoints
  results_dir: outputs/B3/results
  mlruns_dir: outputs/B3/mlruns
